// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABQmkg4j1P9jeGneJZ6hCfFkssY4dlOeQ',
    appId: '1:1076750775032:web:d9701bbf0c3a400ba4c10d',
    messagingSenderId: '1076750775032',
    projectId: 'trivialy-64a5d',
    authDomain: 'trivialy-64a5d.firebaseapp.com',
    storageBucket: 'trivialy-64a5d.firebasestorage.app',
    measurementId: 'G-Y0VQCELSCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiY6-n_ggwrAqBtISZQrwz3GnlnvaoMek',
    appId: '1:1076750775032:android:f3167af331bdee7ca4c10d',
    messagingSenderId: '1076750775032',
    projectId: 'trivialy-64a5d',
    storageBucket: 'trivialy-64a5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLOIvY5vRU1GcLHLiA5CXdYlD51tQw31o',
    appId: '1:1076750775032:ios:5a67e32aa518681fa4c10d',
    messagingSenderId: '1076750775032',
    projectId: 'trivialy-64a5d',
    storageBucket: 'trivialy-64a5d.firebasestorage.app',
    iosBundleId: 'com.example.trivialy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLOIvY5vRU1GcLHLiA5CXdYlD51tQw31o',
    appId: '1:1076750775032:ios:5a67e32aa518681fa4c10d',
    messagingSenderId: '1076750775032',
    projectId: 'trivialy-64a5d',
    storageBucket: 'trivialy-64a5d.firebasestorage.app',
    iosBundleId: 'com.example.trivialy',
  );
}
